# Generated by Django 2.2.1 on 2019-05-10 06:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qtitle', models.CharField(max_length=255)),
                ('qdetail', models.CharField(max_length=255, unique=True)),
                ('qvotes', models.IntegerField(default=1)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('mtp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.Meetup')),
            ],
        ),
    ]
